name: NotLuna
author: Stl4iix
api: 3.0.0
version: 1.0.0
main: fr.luna.core.Main

permissions:
  cmd.joueur.discord:
    default: true
  cmd.joueur.spawn:
    default: true
  cmd.joueur.seemoney:
    default: true

  cmd.staff.addmoney:
    default: op
  cmd.staff.removemoney:
    default: op
